FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential=12.9 python3-dev=3.8.5 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . /app

RUN useradd -m myuser && chown -R myuser:myuser /app
USER myuser

CMD ["python", "app.py"]