name: CI/CD for Docker App

on:
  push:
    branches:
      - lab3
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Checkout кода
      - name: Checkout code
        uses: actions/checkout@v2

      # Шаг 2: Установка Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Шаг 3: Логинимся в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Шаг 4: Сборка Docker-образа
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/lab3-docker:ci_cd lab3/

      # Шаг 5: Публикация Docker-образа на Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/lab3-docker:ci_cd

      # Шаг 6: Проверка работы контейнера (тесты)
      - name: Run Docker container and tests
        run: |
          docker run -d -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/lab3-docker:ci_cd
          sleep 5
          curl http://localhost:3000
