name: CI/CD for Docker App

on:
  push:
    branches:
      - lab3
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Checkout кода
      - name: Checkout code
        uses: actions/checkout@v2

      # Шаг 2: Установка Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Bitwarden secrets
          uses: bitwarden/sm-action@v2
          with:
            access_token: ${{ secrets.BITWARDEN_ACCESS_TOKEN }}
            base_url: https://vault.bitwarden.com
            secrets: |
              c7ba33b0-14d6-4aae-9c06-b20f010dab86 > DOCKERHUB_USERNAME
              7998fe1d-dcc5-4613-ac5d-b20f010cb5ed > DOCKERHUB_TOKEN

      # Шаг 3: Логинимся в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      # Шаг 4: Сборка Docker-образа
      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/lab3-docker:ci_cd lab3/

      # Шаг 5: Публикация Docker-образа на Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ env.DOCKERHUB_USERNAME }}/lab3-docker:ci_cd

      # Шаг 6: Проверка работы контейнера (тесты)
      - name: Run Docker container and tests
        run: |
          docker run -d -p 3000:3000 ${{ env.DOCKERHUB_USERNAME }}/lab3-docker:ci_cd
          sleep 5
          curl http://localhost:3000
